apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: schematic-portal
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
